RSWEBProject/Models/Order.cs
using System.ComponentModel.DataAnnotations;
namespace RSWEBProject.Models
{
    public class Order
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public Restaurant? Restaurant { get; set; }
        public int ClientId { get; set; }
        public Client? Client { get; set; }
        public int? SerialNumber { get; set; }
        public int? Price { get; set; }
    }
}

RSWEBProject/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEBProject.Areas.Identity.Data;
using RSWEBProject.Data;
using RSWEBProject.Models;
using RSWEBProject.ViewModels;

namespace RSWEBProject.Controllers
{
    public class ClientsController : Controller
    {
        private readonly RSWEBProjectContext _context;
        private UserManager<RSWEBProjectUser> _userManager;
        public ClientsController(RSWEBProjectContext context, UserManager<RSWEBProjectUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [Authorize(Roles = "Admin")]
        // GET: Clients
        public async Task<IActionResult> Index(string fullName, string address, string phoneNumber, string email)
        {
            IQueryable<Client> clients = _context.Client.AsQueryable();
            if (!string.IsNullOrEmpty(fullName))
            {
                if (fullName.Contains(" "))
                {
                    string[] names = fullName.Split(" ");
                    clients = clients.Where(x => x.FirstName.Contains(names[0]) || x.LastName.Contains(names[1]) ||
                    x.FirstName.Contains(names[1]) || x.LastName.Contains(names[0])); ;
                }
                else
                {
                    clients = clients.Where(x => x.FirstName.Contains(fullName) || x.LastName.Contains(fullName));
                }
            }
            if (!string.IsNullOrEmpty(address))
            {
                clients = clients.Where(x => x.Address == address);
            }
            if (!string.IsNullOrEmpty(phoneNumber))
            {
                clients = clients.Where(x => x.PhoneNumber == phoneNumber);
            }
            if (!string.IsNullOrEmpty(email))
            {
                clients = clients.Where(p => p.Email == email);
            }
            clients = clients.Include(m => m.Orders).ThenInclude(m => m.Restaurant);
            var movieGenreVM = new ClientQuery
            {
                
                Clients = await clients.ToListAsync()
            };
            return View(movieGenreVM);




           
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userLoggedInId = HttpContext.Session.GetString("UserLoggedIn");
            if (userLoggedInId != id.ToString() && userLoggedInId != "Admin")
            {
                return Forbid();
            }
            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            ClientPicture viewmodel = new ClientPicture
            {
                client = client,
                ProfilePictureName = client.ProfilePicture
            };

            return View(viewmodel);




            
        }
        [Authorize(Roles = "Admin")]
        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,PhoneNumber,Address,Email,ProfilePicture")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }
        [Authorize(Roles = "Admin")]
        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }
        [Authorize(Roles = "Admin")]
        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,PhoneNumber,Address,Email,ProfilePicture")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }
        [Authorize(Roles = "Admin")]
        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }
        [Authorize(Roles = "Admin")]
        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Client == null)
            {
                return Problem("Entity set 'RSWEBProjectContext.Client'  is null.");
            }
            var client = await _context.Client.FindAsync(id);
            if (client != null)
            {
                _context.Client.Remove(client);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
          return (_context.Client?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        [Authorize(Roles = "Delivery Man")]
        // GET: ViewOrders
        public async Task<IActionResult> ViewOrders(int id)
        {
            var kolokviumContext = _context.Order.Where(x => x.RestaurantId == id).Include(m => m.Restaurant).Include(a => a.Client);
            return View(await kolokviumContext.ToListAsync());
        }

        [Authorize(Roles = "Client")]
        // GET: Clients/EditPicture/5
        public async Task<IActionResult> EditPicture(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = _context.Client.Where(x => x.Id == id).Include(x => x.Orders).First();
            if (client == null)
            {
                return NotFound();
            }

            var restaurants = _context.Restaurant.AsEnumerable();
            restaurants = restaurants.OrderBy(s => s.Name);

            ClientPicture viewmodel = new ClientPicture
            {
                client = client,
                ProfilePictureName = client.ProfilePicture
            };

            return View(viewmodel);
        }
        [Authorize(Roles = "Client")]
        // POST: Clients/EditPicture/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPicture(long id, ClientPicture viewmodel)
        {
            if (id != viewmodel.client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (viewmodel.ProfilePictureFile != null)
                    {
                        string uniqueFileName = UploadedFile(viewmodel);
                        viewmodel.client.ProfilePicture = uniqueFileName;
                    }
                    else
                    {
                        viewmodel.client.ProfilePicture = viewmodel.ProfilePictureName;
                    }

                    _context.Update(viewmodel.client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(viewmodel.client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = viewmodel.client.Id });
            }
            return View(viewmodel);
        }

        private string UploadedFile(ClientPicture viewmodel)
        {
            string uniqueFileName = null;

            if (viewmodel.ProfilePictureFile != null)
            {

RSWEBProject/Views/Orders/Create.cshtml
@model RSWEBProject.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class ="form-control" asp-items="ViewBag.RestaurantId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId" readonly="@(true)"></select>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" readonly="@(true)" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Restaurants" asp-action="ViewOrders" asp-route-id="@Model?.Client.Id">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/Orders/Delete.cshtml
@model RSWEBProject.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Restaurant.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RSWEBProject/Views/Orders/Details.cshtml
@model RSWEBProject.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Restaurant.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RSWEBProject/Views/Orders/Edit.cshtml
@model RSWEBProject.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class="form-control" asp-items="ViewBag.RestaurantId"></select>
                <span asp-validation-for="RestaurantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/Orders/EditAsClient.cshtml
@model RSWEBProject.Models.Order

@{
    ViewData["Title"] = "EditAsClient";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditAsClient">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class="form-control" asp-items="ViewBag.RestaurantId" readonly="@(true)"></select>
                <span asp-validation-for="RestaurantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId" readonly="@(true)"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" readonly="@(true)" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"  />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Restaurants" asp-action="ViewOrders" asp-route-id="@Model?.Client.Id">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/Orders/EditAsDeliveryMan.cshtml
@model RSWEBProject.Models.Order

@{
    ViewData["Title"] = "EditAsDeliveryMan";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditAsDeliveryMan">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class="form-control" asp-items="ViewBag.RestaurantId" readonly="@(true)"></select>
                <span asp-validation-for="RestaurantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId" readonly="@(true)"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" readonly="@(true)" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
     <a asp-controller="Clients" asp-action="ViewOrders" asp-route-id="@Model?.Restaurant.Id">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/Orders/Index.cshtml
@model IEnumerable<RSWEBProject.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Orders</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>