RSWEBProject/Controllers/DeliveryMenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEBProject.Areas.Identity.Data;
using RSWEBProject.Data;
using RSWEBProject.Models;
using RSWEBProject.ViewModels;

namespace RSWEBProject.Controllers
{
    public class DeliveryMenController : Controller
    {
        private readonly RSWEBProjectContext _context;
        private UserManager<RSWEBProjectUser> _userManager;
        public DeliveryMenController(RSWEBProjectContext context, UserManager<RSWEBProjectUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [Authorize(Roles = "Admin")]
        // GET: DeliveryMen
        public async Task<IActionResult> Index(string fullName)
        {
            IQueryable<DeliveryMan> deliveryMen = _context.DeliveryMan.AsQueryable();
            if (!string.IsNullOrEmpty(fullName))
            {
                if (fullName.Contains(" "))
                {
                    string[] names = fullName.Split(" ");
                    deliveryMen = deliveryMen.Where(x => x.FirstName.Contains(names[0]) || x.LastName.Contains(names[1]) ||
                    x.FirstName.Contains(names[1]) || x.LastName.Contains(names[0])); ;
                }
                else
                {
                    deliveryMen = deliveryMen.Where(x => x.FirstName.Contains(fullName) || x.LastName.Contains(fullName));
                }
            }
            
            deliveryMen = deliveryMen.Include(m => m.Restaurants).ThenInclude(m => m.Orders).ThenInclude(m => m.Client); 
            var movieGenreVM = new DeliveryManQuery
            {

                DeliveryMen = await deliveryMen.ToListAsync()
            };
            return View(movieGenreVM);
        }
        // GET: DeliveryMen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userLoggedInId = HttpContext.Session.GetString("UserLoggedIn");
            if (userLoggedInId != id.ToString() && userLoggedInId != "Admin")
            {
                return Forbid();
            }
            var deliveryMan = await _context.DeliveryMan
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deliveryMan == null)
            {
                return NotFound();
            }

            DeliveryManPicture viewmodel = new DeliveryManPicture
            {
                deliveryMan = deliveryMan,
                ProfilePictureName = deliveryMan.ProfilePicture
            };

            return View(viewmodel);
        }
        [Authorize(Roles = "Admin")]
        // GET: DeliveryMen/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: DeliveryMen/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,HireDate,ProfilePicture")] DeliveryMan deliveryMan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(deliveryMan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(deliveryMan);
        }
        [Authorize(Roles = "Admin")]
        // GET: DeliveryMen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DeliveryMan == null)
            {
                return NotFound();
            }

            var deliveryMan = await _context.DeliveryMan.FindAsync(id);
            if (deliveryMan == null)
            {
                return NotFound();
            }
            return View(deliveryMan);
        }
        [Authorize(Roles = "Admin")]
        // POST: DeliveryMen/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,HireDate,ProfilePicture")] DeliveryMan deliveryMan)
        {
            if (id != deliveryMan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(deliveryMan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeliveryManExists(deliveryMan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deliveryMan);
        }
        [Authorize(Roles = "Admin")]
        // GET: DeliveryMen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DeliveryMan == null)
            {
                return NotFound();
            }

            var deliveryMan = await _context.DeliveryMan
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deliveryMan == null)
            {
                return NotFound();
            }

            return View(deliveryMan);
        }
        [Authorize(Roles = "Admin")]
        // POST: DeliveryMen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DeliveryMan == null)
            {
                return Problem("Entity set 'RSWEBProjectContext.DeliveryMan'  is null.");
            }
            var deliveryMan = await _context.DeliveryMan.FindAsync(id);
            if (deliveryMan != null)
            {
                _context.DeliveryMan.Remove(deliveryMan);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeliveryManExists(int id)
        {
          return (_context.DeliveryMan?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        [Authorize(Roles = "Delivery Man")]
        // GET: DeliveryMen/EditPicture/5
        public async Task<IActionResult> EditPicture(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryMan = _context.DeliveryMan.Where(x => x.Id == id).First();
            if (deliveryMan == null)
            {
                return NotFound();
            }

            DeliveryManPicture viewmodel = new DeliveryManPicture
            {
                deliveryMan = deliveryMan,
                ProfilePictureName = deliveryMan.ProfilePicture
            };
            
            return View(viewmodel);
        }
        [Authorize(Roles = "Delivery Man")]
        // POST: DeliveryMen/EditPicture/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPicture(long id, DeliveryManPicture viewmodel)
        {
            if (id != viewmodel.deliveryMan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (viewmodel.ProfilePictureFile != null)
                    {
                        string uniqueFileName = UploadedFile(viewmodel);
                        viewmodel.deliveryMan.ProfilePicture = uniqueFileName;
                    }
                    else
                    {
                        viewmodel.deliveryMan.ProfilePicture = viewmodel.ProfilePictureName;
                    }

                    _context.Update(viewmodel.deliveryMan);
                   
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeliveryManExists(viewmodel.deliveryMan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = viewmodel.deliveryMan.Id });
            }
            return View(viewmodel);
        }
        private string UploadedFile(DeliveryManPicture viewmodel)
        {
            string uniqueFileName = null;

            if (viewmodel.ProfilePictureFile != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/profilePictures");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(viewmodel.ProfilePictureFile.FileName);
                string fileNameWithPath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {

RSWEBProject/Views/DeliveryMen/Create.cshtml
@model RSWEBProject.Models.DeliveryMan

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DeliveryMan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/DeliveryMen/Delete.cshtml
@model RSWEBProject.Models.DeliveryMan

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeliveryMan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RSWEBProject/Views/DeliveryMen/Details.cshtml
@model RSWEBProject.ViewModels.DeliveryManPicture

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DeliveryMan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
           Profile picture:
        </dt>
        <dd class = "col-sm-10">
            <img src="~/profilePictures/@Model.deliveryMan.ProfilePicture"
                class="rounded-circle"
                height="40" width="40"
                asp-append-version="true" />
        </dd> 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.deliveryMan.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.deliveryMan.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.deliveryMan.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.deliveryMan.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.deliveryMan.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.deliveryMan.HireDate)
        </dd>
        
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.deliveryMan.Id">Edit</a>
    }
    |
    @if (User.Identity.IsAuthenticated && User.IsInRole("Delivery Man"))
    {
        <a asp-action="EditPicture" asp-route-id="@Model?.deliveryMan.Id">Edit Picture</a>
    }
    |
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Index">Back to List</a>
    }
    |
    @if (User.Identity.IsAuthenticated && User.IsInRole("Delivery Man"))
    {
        <a asp-controller="Restaurants" asp-action="ViewRestaurants" asp-route-id="@Model?.deliveryMan.Id">Check Restaurants</a>
    }
</div>

RSWEBProject/Views/DeliveryMen/Edit.cshtml
@model RSWEBProject.Models.DeliveryMan

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DeliveryMan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/DeliveryMen/EditPicture.cshtml
@model RSWEBProject.ViewModels.DeliveryManPicture

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DeliveryMan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPicture" enctype="multipart/form-data" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="deliveryMan.Id" />
            <div class="form-group"  style="display:none">
                <label asp-for="deliveryMan.FirstName" class="control-label"></label>
                <input asp-for="deliveryMan.FirstName" class="form-control" />
                <span asp-validation-for="deliveryMan.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="deliveryMan.LastName" class="control-label"></label>
                <input asp-for="deliveryMan.LastName" class="form-control" />
                <span asp-validation-for="deliveryMan.LastName" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="deliveryMan.HireDate" class="control-label"></label>
                <input asp-for="deliveryMan.HireDate" class="form-control" />
                <span asp-validation-for="deliveryMan.HireDate" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none" >
                <label asp-for="deliveryMan.ProfilePicture" class="control-label"></label>
                <input asp-for="deliveryMan.ProfilePicture" class="form-control" />
                <span asp-validation-for="deliveryMan.ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePictureFile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="ProfilePictureFile" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                </div>
                <span asp-validation-for="ProfilePictureFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details">Back to Details</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/DeliveryMen/Index.cshtml
@model RSWEBProject.ViewModels.DeliveryManQuery

@{
    ViewData["Title"] = "Index";
}

<h1>Delivery Men</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="DeliveryMen" asp-action="Index" method="get">
    <p>
        Name: <input type="text" asp-for="FullName" />
        
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Profile Picture
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryMen[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryMen[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryMen[0].HireDate)
            </th>
            
            <th>
                Check Restaurants
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.DeliveryMen) {
        <tr>
            <td>
               
            <img src="~/profilePictures/@item.ProfilePicture"
                class="rounded-circle"
                height="70" width="70"
                asp-append-version="true" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            
            <td>
                <a asp-controller="Restaurants" asp-action="ViewRestaurants" asp-route-id="@item.Id">Check Restaurants</a>
            </td>
            <td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    }
                    |
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Delivery Man"))
                    {
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                    }
                    |
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                </td>
        </tr>
}
    </tbody>
</table>