RSWEBProject/Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;
namespace RSWEBProject.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Location { get; set; }
        public string? Type { get; set; }
        public int? DeliveryManId { get; set; }
        [Display(Name = "Delivery Man")]
        public DeliveryMan? DeliveryMan { get; set; }
        public ICollection<Order>? Orders { get; set; }
    }
}

RSWEBProject/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSWEBProject.Data;
using RSWEBProject.Models;
using RSWEBProject.ViewModels;

namespace RSWEBProject.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly RSWEBProjectContext _context;

        public RestaurantsController(RSWEBProjectContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Admin")]
        // GET: Restaurants
        public async Task<IActionResult> Index(string type, string name, string location)
        {
            IQueryable<Restaurant> restaurants = _context.Restaurant.AsQueryable();
            IQueryable<string> typeQuery = _context.Restaurant.OrderBy(m => m.Type).Select(m => m.Type).Distinct();
            if (!string.IsNullOrEmpty(name))
            {
                restaurants = restaurants.Where(s => s.Name.Contains(name));
            }
            if (!string.IsNullOrEmpty(location))
            {
                restaurants = restaurants.Where(x => x.Location == location);
            }
            if (!string.IsNullOrEmpty(location))
            {
                restaurants = restaurants.Where(x => x.Location == location);
            }
            if (!string.IsNullOrEmpty(type))
            {
                restaurants = restaurants.Where(p => p.Type == type);
            }
            restaurants = restaurants.Include(m => m.DeliveryMan)
            .Include(m => m.Orders).ThenInclude(m => m.Client);
            var movieGenreVM = new RestaurantQuery
            {
                Types = new SelectList(await typeQuery.ToListAsync()),
                Restaurants = await restaurants.ToListAsync()
            };
            return View(movieGenreVM);




         
        }
        [Authorize(Roles = "Admin")]
        // GET: Restaurants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Restaurant == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant
                .Include(r => r.DeliveryMan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }
        [Authorize(Roles = "Admin")]
        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["DeliveryManId"] = new SelectList(_context.DeliveryMan, "Id", "Id");
            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Location,Type,DeliveryManId")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(restaurant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeliveryManId"] = new SelectList(_context.DeliveryMan, "Id", "Id", restaurant.DeliveryManId);
            return View(restaurant);
        }
        [Authorize(Roles = "Admin")]
        // GET: Restaurants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Restaurant == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant.FindAsync(id);
            if (restaurant == null)
            {
                return NotFound();
            }
            ViewData["DeliveryManId"] = new SelectList(_context.DeliveryMan, "Id", "Id", restaurant.DeliveryManId);
            return View(restaurant);
        }
        [Authorize(Roles = "Admin")]
        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Location,Type,DeliveryManId")] Restaurant restaurant)
        {
            if (id != restaurant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists(restaurant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeliveryManId"] = new SelectList(_context.DeliveryMan, "Id", "Id", restaurant.DeliveryManId);
            return View(restaurant);
        }
        [Authorize(Roles = "Admin")]
        // GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Restaurant == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant
                .Include(r => r.DeliveryMan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }
        [Authorize(Roles = "Admin")]
        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Restaurant == null)
            {
                return Problem("Entity set 'RSWEBProjectContext.Restaurant'  is null.");
            }
            var restaurant = await _context.Restaurant.FindAsync(id);
            if (restaurant != null)
            {
                _context.Restaurant.Remove(restaurant);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(int id)
        {
          return (_context.Restaurant?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        [Authorize(Roles = "Client")]
        // GET: ViewOrders
        public async Task<IActionResult> ViewOrders(int id)
        {
            var userLoggedInId = HttpContext.Session.GetString("UserLoggedIn");
           // if (userLoggedInId != id.ToString() && userLoggedInId != "Admin")
           // {
             //   return Forbid();
            //}
            var kolokviumContext = _context.Order.Where(x => x.ClientId == int.Parse(HttpContext.Session.GetString("UserLoggedIn"))).Include(m => m.Client).Include(a => a.Restaurant);
            
          return View(await kolokviumContext.ToListAsync());
        }
        [Authorize(Roles = "Delivery Man")]
        // GET: ViewRestaurants
        public async Task<IActionResult> ViewRestaurants(int id, string type, string name, string location)
        {
            var userLoggedInId = HttpContext.Session.GetString("UserLoggedIn");
            if (userLoggedInId != id.ToString() && userLoggedInId != "Admin")
            {
                return Forbid();
            }
            IQueryable<Restaurant> restaurants = _context.Restaurant.AsQueryable();
            restaurants = restaurants.Where(x => x.DeliveryManId == id).Include(m => m.DeliveryMan);
            IQueryable<string> typeQuery = _context.Restaurant.OrderBy(m => m.Type).Select(m => m.Type).Distinct();
            if (!string.IsNullOrEmpty(name))
            {
                restaurants = restaurants.Where(s => s.Name.Contains(name));
            }
            if (!string.IsNullOrEmpty(location))
            {
                restaurants = restaurants.Where(x => x.Location == location);
            }
            if (!string.IsNullOrEmpty(location))
            {
                restaurants = restaurants.Where(x => x.Location == location);
            }
            if (!string.IsNullOrEmpty(type))
            {
                restaurants = restaurants.Where(p => p.Type == type);
            }
            restaurants = restaurants.Include(m => m.DeliveryMan)
            .Include(m => m.Orders).ThenInclude(m => m.Client);
            var movieGenreVM = new RestaurantQuery
            {
                Types = new SelectList(await typeQuery.ToListAsync()),
                Restaurants = await restaurants.ToListAsync()
            };
            return View(movieGenreVM);
        }
    }
}

RSWEBProject/Views/Restaurants/Create.cshtml
@model RSWEBProject.Models.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryManId" class="control-label"></label>
                <select asp-for="DeliveryManId" class ="form-control" asp-items="ViewBag.DeliveryManId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/Restaurants/Delete.cshtml
@model RSWEBProject.Models.Restaurant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryMan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeliveryMan.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RSWEBProject/Views/Restaurants/Details.cshtml
@model RSWEBProject.Models.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryMan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeliveryMan.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RSWEBProject/Views/Restaurants/Edit.cshtml
@model RSWEBProject.Models.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryManId" class="control-label"></label>
                <select asp-for="DeliveryManId" class="form-control" asp-items="ViewBag.DeliveryManId"></select>
                <span asp-validation-for="DeliveryManId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSWEBProject/Views/Restaurants/Index.cshtml
@model RSWEBProject.ViewModels.RestaurantQuery

@{
    ViewData["Title"] = "Index";
}

<h1>Restaurants</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Restaurants" asp-action="Index" method="get">
    <p>
        Name: <input type="text" asp-for="Name" />
        Type:
        <select asp-for="Type" asp-items="Model.Types">
            <option value="">All</option>
        </select>
        Location:
        <input type="text" asp-for="Location" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].DeliveryMan)
            </th>
            <th>
                Orders
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Restaurants) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryMan.FullName)
            </td>
            <td>
                <a asp-controller="Clients" asp-action="ViewOrders" asp-route-id="@item.Id">Check Orders</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RSWEBProject/Views/Restaurants/ViewOrders.cshtml
@model IEnumerable<RSWEBProject.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Orders</h1>
<a asp-controller="Orders" asp-action="Create">Create</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Client"))
                {<a asp-controller="Orders" asp-action="EditAsClient" asp-route-id="@item.Id">Edit</a>} |
                 |
                @if (User.Identity.IsAuthenticated && User.IsInRole("Client"))
                {<a asp-controller="Clients" asp-action="Details" asp-route-id="@item.Client.Id">Details</a>} 
            </td>
        </tr>
}
    </tbody>
</table>

RSWEBProject/Views/Restaurants/ViewRestaurants.cshtml
@model RSWEBProject.ViewModels.RestaurantQuery

@{
    ViewData["Title"] = "Index";
}

<h1>Restaurants</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Restaurants" asp-action="Index" method="get">
    <p>
        Name: <input type="text" asp-for="Name" />
        Type:
        <select asp-for="Type" asp-items="Model.Types">
            <option value="">All</option>
        </select>
        Location:
        <input type="text" asp-for="Location" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurants[0].DeliveryMan)
            </th>
            <th>
                Orders
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Restaurants) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryMan.FullName)
            </td>
            <td>
                <a asp-controller="Clients" asp-action="ViewOrders" asp-route-id="@item.Id">Check Orders</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-controller="DeliveryMen" asp-action="Details" asp-route-id="@item.DeliveryMan.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>